name: CI

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: app' tests
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: automated tests
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci #cf. https://docs.npmjs.com/cli/v9/commands/npm-ci
      - run: npm run test
  # Build and publish the Docker image to the GCP Artifact Registry
  build-publish:
    needs: test
    runs-on: ubuntu-latest
    environment: gcp
    name: build docker image and push it to the GAR
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.head.ref }}
      - name: build code
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GCP_REGISTRY_REGION }}
          username: _json_key
          password: ${{ secrets.GCP_REGISTRY_KEY }}
      - run: docker build -t ${{ secrets.GCP_REGISTRY_ALL_PATH_IMAGE }}/auth-workshop-api:${{ github.sha }} .
      - run: docker push ${{ secrets.GCP_REGISTRY_ALL_PATH_IMAGE }}/auth-workshop-api:${{ github.sha }}
  deploy-to-cloud-run:
    needs: build-publish
    runs-on: ubuntu-latest
    environment: gcp
    name: deploy the previously built image to Cloud Run
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.head.ref }}
      # Setup gcloud CLI
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_REGISTRY_KEY }}"
      # Deploy to Cloud Run
      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "auth-workshop-api"
          image: "${{ secrets.GCP_REGISTRY_ALL_PATH_IMAGE }}/auth-workshop-api:${{ github.sha }}"
          env_vars: |
            NODE_ENV=production
            SECRET_COOKIE=${{ secrets.SECRET_COOKIE}}
            DATABASE_PASSWORD=${{ secrets.SECRET_DATABASE_PASSWORD}}
          flags: "--port=8080"
          region: "europe-west1"
      - name: "deploy output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'